#!/bin/sh
#<?php ob_end_clean(); goto start; ?>

WEB_SERVER_ADDRESS="127.0.0.1"
WEB_SERVER_PORT="8080"

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`

# Help block
#{{{

HELP="
Description: The script starts the php built-in web server with authorization.
Usage: ${BASENAME} <user_name> <path_to_docroot>
"

if test "${1}" = "-h" -o "${1}" = "--help"
then
	echo "${HELP}"
	exit 0
fi

#}}}

# Echo functions
#{{{

error ()
{
	/usr/bin/echo "Error: ${BASENAME} - ${1}" >&2
	return 255
}

notice ()
{
	/usr/bin/echo "${BASENAME} - ${1}"
	return 0
}

#}}}

# Change user
#{{{

UID=`/usr/bin/id -r -u`
GID=`/usr/bin/id -r -g`

if test $UID -eq 0 -o $GID -eq 0
then

	if test -z "${1}"
	then
		error "User name not set"
		exit 255
	fi
	export WEB_SERVER_USER="${1}"
	
	if test -z "${2}"
	then
		error "Path to docroot not set"
		exit 255
	fi
	export WEB_SERVER_DOCROOT="${2}"
	
	/usr/bin/su -P -s /bin/sh -l "${WEB_SERVER_USER}"  -w "WEB_SERVER_USER,WEB_SERVER_DOCROOT" -c ${FILE}
	exit 0
fi

#}}}

# Test variables
#{{{

if test -z "${WEB_SERVER_USER}"
	then
	error "'WEB_SERVER_USER' is not set"
	exit 255
fi

if test -z "${WEB_SERVER_DOCROOT}"
	then
	error "'WEB_SERVER_DOCROOT' is not set"
	exit 255
fi

#}}}

export WEB_SERVER_PASSWORD=`/usr/bin/apg -n 1 -m 6 -x 6 -M NCL`

/usr/bin/echo "uid: ${UID}, gid: ${GID}"
/usr/bin/echo "document root: ${WEB_SERVER_DOCROOT}"
/usr/bin/echo "user: ${WEB_SERVER_USER}"
/usr/bin/echo "password: ${WEB_SERVER_PASSWORD}"

/usr/bin/php -d auto_prepend_file=${FILE} -t ${WEB_SERVER_DOCROOT} -S ${WEB_SERVER_ADDRESS}:${WEB_SERVER_PORT}
exit $?

<?php start:
require(__DIR__.'/include/block/authorization.php');

