#!/usr/bin/php
<?php

define('DEBUG', true);

set_include_path(__DIR__.'/include');
require_once('class/Args.php');
require_once('class/DB.php');
require_once('class/Action.php');
require_once('class/Data.php');

if(true) // Args initialization
{//{{{//

	Args::$description = "Console version of SEO tool";
	
	Args::add([
		"-t", "--test", NULL, "Start only tests part",
		function () {
			define("TEST", true);
		}, false
	]);
	
	Args::add([
		"-c", "--create", NULL, "Create dabase tables",
		function () {
			define("ACTION_CREATE_TABLE", true);
		}, false
	]);
	
	Args::apply();
	
}//}}}//

if(true) // Load config
{//{{{//

	$return = getenv('HOME', true);
	if(!is_string($return)) {
		trigger_error("Can't get 'HOME' environment", E_USER_ERROR);
		exit(255);
	}
	$home = $return;
	
	$file = "{$home}/.config/v3bd3w/seo.php";
	require_once($file);
	
}//}}}//

function test()
{//{{{//

	if(!true) // Action::save_list_item
	{//{{{//
		$item = [
			"host" => "example.com",
			"title" => "This is example title",
			"url" => "https://example.com/index.html",			
		];
		$return = Action::save_list_item($item);
		var_dump($return);
	}//}}}//
	
	if(!true) // Action::save_titles
	{//{{{//
		$return = Action::save_titles();
		var_dump($return);
	}//}}}//
	
	if(!true) // Data::insert_host
	{//{{{//
		$return = Data::insert_host("example.com");
		var_dump($return);
	}//}}}//
	
	if(!true) // Data sql functions
	{//{{{//
		//$return = Data::select_host("localhost");
		//$return = Data::insert_title(2, "Example title", "https://example.com/index.html");
		//$return = Data::select_title("https://example.com/index.html");
		var_dump($return);
	}//}}}//
	
}//}}}//

function main(array $argv)
{
	DB::open(CONFIG["database"]["host"], CONFIG["database"]["user"], CONFIG["database"]["password"], CONFIG["database"]["name"]);

	if(defined('TEST') && TEST === true)
	{//{{{//
		$return = test();
		return(true);
	}//}}}//
	
	if(defined('ACTION_CREATE_TABLE') && ACTION_CREATE_TABLE === true)
	{//{{{//
		$return = Data::create_tables();
		if(!$return) {
			trigger_error("Can't create database tables", E_USER_WARNING);
			return(false);
		}
		return(true);
	}//}}}//
	
	return(true);
}

$return = main($argv);
if($return !== true) {
	trigger_error("The 'main' call returned an error", E_USER_ERROR);
	exit(255);
}

exit(0);
