#!/bin/sh

### init
#{{{

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`

APACHE2_DIR="/etc/apache2"
PHP_DIR="/etc/php/8.2/apache2"
SYSTEM_DIR="/lib/systemd/system"

HELP="
Description: Setting up isolated LAMP on system
Usage: ${BASENAME}
"
if test "${1}" = "-h" -o "${1}" = "--help"
then
	echo "${HELP}"
	exit 0
fi

#}}}

### functions
#{{{

error ()
{
	/usr/bin/echo -e -n "\nERROR: ${BASENAME} - ${1}\n" >&2
	return 255
}

notice ()
{
	/usr/bin/echo -e -n "\nSTAGE: ${1}\n"
	if test ${?} -ne 0
	then
		return 255
	fi
	return 0
}

run ()
{

	COMMAND="${*}"
	echo "\n> ${COMMAND}"
	${COMMAND}
	if test ${?} -ne 0
	then
		error "Running the command failed with an error"
		exit 255
	fi
	return 0
	
}

remove ()
{
	FILE_NAME=$1
	if test -f ${FILE_NAME}
	then
		run rm -v ${FILE_NAME}
	fi
}

#}}}

if ! true && notice "Template"
then #{{{
	echo "Script block template"
fi #}}}

if  true && notice "remove site manager and isolated aplications starters"
then #{{{

FILE_NAMES="
	/usr/local/sbin/site-manager
	/usr/local/bin/isolated_firefox
	/usr/share/applications/isolated_firefox.desktop
	/usr/local/bin/isolated_root_terminal
	/usr/share/applications/isolated_root_terminal.desktop
"
for FILE_NAME in ${FILE_NAMES}
do
	remove ${FILE_NAME}
done

fi #}}}

if  true && notice "disable and remove isolated services"
then #{{{

SERVICE_NAMES="
	isolated_mariadb.service
	isolated_apache2.service
	isolated_network.service
"
for SERVICE_NAME in ${SERVICE_NAMES}
do
	if test -f ${SYSTEM_DIR}/${SERVICE_NAME}
	then
		systemctl is-active ${SERVICE_NAME} 1> /dev/null 2> /dev/null
		if test $? -eq 0
		then
			run systemctl stop ${SERVICE_NAME}
		fi
	fi
	
	STATE=`systemctl show ${SERVICE_NAME} | grep UnitFileState`
	if test "${STATE}" != "UnitFileState=disabled"
	then
		run systemctl disable ${SERVICE_NAME}
	fi
	
	remove ${SYSTEM_DIR}/${SERVICE_NAME}
done

remove /usr/local/sbin/isolated_network
remove /usr/local/bin/sendmail_cap

fi #}}}

exit 0

