#!/bin/sh -e

/usr/bin/apt install tzdata locales keyboard-configuration console-setup
/usr/sbin/dpkg-reconfigure tzdata 
/usr/sbin/dpkg-reconfigure locales
/usr/sbin/dpkg-reconfigure keyboard-configuration
/usr/sbin/dpkg-reconfigure console-setup

/usr/bin/apt install info man-db manpages manpages-dev manpages-posix manpages-posix-dev
/usr/bin/apt install dict dictd mueller7-dict
/usr/bin/apt install lynx dnsutils whois geoip-bin telnet nmap wget

/usr/bin/apt install xorg xfwm4 xfce4 xfce4-power-manager xfce4-terminal xfonts-terminus mousepad
/usr/bin/apt install sudo pkexec gparted apg mtools
/usr/bin/apt install chromium transmission-cli gimp
/usr/bin/apt install galculator zathura ristretto
/usr/bin/apt install alsa-utils pulseaudio mplayer mpg123

! /usr/sbin/alsactl -L init

adduser --gecos "" user
chmod 700 /home/user
adduser user sudo
adduser user audio

echo "Base installation complete"
